name: CI Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-gloves-emulator:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout Vortex Engine
      uses: actions/checkout@v3
      with:
        repository: 'StoneOrbits/VortexEngine'
        path: 'VortexTestingFramework/VortexEngine'
        ref: 'gloves'
    - name: Set up MSBuild path
      uses: microsoft/setup-msbuild@v1
    - name: Build
      run: msbuild VortexTestingFramework.sln /p:Configuration=Release /p:Platform=x64
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Binaries
        path: x64/Release/VortexTestingFramework.exe

